# Use topsecretuser/topsecretpass as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: topsecretuser
      MONGO_INITDB_ROOT_PASSWORD: topsecretpass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: topsecretuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: topsecretpass
      ME_CONFIG_MONGODB_URL: mongodb://topsecretuser:topsecretpass@mongo:27017/
      ME_CONFIG_BASICAUTH: false
